name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node: [10.x, 12.x, 13.x, 14.x]
      fail-fast: false

    steps:
      # - name: Set git to use LF on Windows
      #   if: matrix.os == 'windows-latest'
      #   run: |
      #     git config --global core.autocrlf false
      #     git config --global core.eol lf

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Versions
        run: npm version

      - name: Install dependencies
        run: npm ci

      # - name: Check outdated dependencies
      #   run: npm outdated

      # - name: Lint
      #   run: npm run lint

      # - name: Test
      #   run: npm run jest --ci --silent

      - name: Audit dependencies
        run: npm audit

      - name: Build
        run: npm run build
